
services:
  - type: web
    name: kv-vacancy-portal
    env: python
    buildCommand: ""
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
